version: '3.1'

# For local testing
services:
  db:
    image: markushimmel.de:5000/merlinhunt/twistylittlepassages/db
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
