secrets:
  mysql_user_password:
    file: ../../secrets/mysql_user_password
  mysql_root_password:
    file: ../../secrets/mysql_root_password
  judgedaemon_password:
    file: ../../secrets/judgedaemon_password
  postgres_postgres_password:
    file: ../../secrets/postgres_postgres_password
  greatundoing_solution_code:
    file: ../rounds/greatundoing/greatundoing.ans
  helloworld_solution_code:
    file: ../rounds/helloworld/greatundoing.ans
  immortalgame_solution_code:
    file: ../rounds/immortalgame/greatundoing.ans

services:
  immortalgame:
    image: markushimmel.de:5000/merlinhunt/immortalgame/server:latest
    container_name: immortal
    hostname: immortal
    secrets:
      - immortalgame_solution_code
    environment:
      IMMORTALGAME_SOLUTION_CODE_FILE: /run/secrets/immortalgame_solution_code
  greatundoing:
    image: markushimmel.de:5000/merlinhunt/thegreatundoing/server:latest
    container_name: undoing
    hostname: undoing
    secrets:
      - greatundoing_solution_code
    environment:
      GREATUNDOING_SOLUTION_CODE_FILE: /run/secrets/greatundoing_solution_code
  mariadb:
    image: mariadb:latest
    container_name: dj-mariadb
    hostname: dj-mariadb
    secrets:
      - mysql_user_password
      - mysql_root_password
    environment:
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_user_password
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_USER: domjudge
      MYSQL_DATABASE: domjudge
    volumes:
      - /var/lib/mysql:/var/lib/mysql
  domserver:
    restart: always
    image: domjudge/domserver:latest
    container_name: domserver
    hostname: domkeks
    secrets:
      - mysql_user_password
      - mysql_root_password
    environment:
      MYSQL_HOST: mariadb
      MYSQL_USER: domjudge
      MYSQL_DATABASE: domjudge
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_user_password
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
  judgehost:
    restart: always
    hostname: judgehost
    image: domjudge/judgehost:latest
    secrets:
      - judgedaemon_password
    environment:
      DAEMON_ID: 0
      JUDGEDAEMON_PASSWORD_FILE: /run/secrets/judgedaemon_password
      DOMSERVER_BASE_URL: http://domkeks/
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  nginx:
    restart: always
    hostname: nginx
    container_name: nginx
    image: markushimmel.de:5000/merlinhunt/nginx
    build:
      dockerfile: Dockerfile-nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/www/certs:/var/www/certs
      - ../../files:/var/www/files
  twisty:
    restart: always
    hostname: twisty
    container_name: twisty
    image: markushimmel.de:5000/merlinhunt/twistylittlepassages/db
    secrets:
      - postgres_postgres_password
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_postgres_password
    ports:
      - 5432:5432
  hello:
    restart: always
    hostname: hello
    container_name: hello
    image: markushimmel.de:5000/merlinhunt/hello/server
    secrets:
      - helloworld_solution_code
    environment:
      HELLOWORLD_SOLUTION_CODE_FILE: /run/secrets/helloworld_solution_code
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    hostname: gitlab
    container_name: gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.markushimmel.de'
        gitlab_rails['gitlab_shell_ssh_port'] = 2222
        gitlab_rails['lfs_enabled'] = true
        letsencrypt['enable'] = false
        nginx['listen_https'] = false
        nginx['listen_port'] = 80
        # Add any other gitlab.rb configuration here, each on its own line
    ports:
      - '2222:22'
    volumes:
      - '/var/lib/gitlab/config:/etc/gitlab'
      - '/var/lib/gitlab/logs:/var/log/gitlab'
      - '/var/lib/gitlab/data:/var/opt/gitlab'
    shm_size: '256m'
