services:
  registry:
    image: registry:2
    container_name: registry
    hostname: registry
    ports:
      - 5000:5000
    environment:
      REGISTRY_HTTP_ADDR: 0.0.0.0:5000
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/certificate.crt
      REGISTRY_HTTP_TLS_KEY: /certs/certificate.key
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
    volumes:
      - /var/registry:/var/lib/registry
      - /var/www/certs:/certs
      - /var/www/auth:/auth
    networks:
      - infra

networks:
  infra:
    driver: bridge
    name: infra
