PROBLEMS := accessgranted helloworld redacted immortalgame twistylittlepassages zweiwalkueren buggyrelay hafenrundfahrt greatundoing
SERVERPROBLEMS := immortalgame greatundoing twistylittlepassages
SECRETSUFFIX := This is the secret suffix for generating flags for the main contest

include ../make/contest.mk
