PROBLEMS := accessgranted helloworld redacted immortalgame buggyrelay zweiwalkueren twistylittlepassages kleinehafenrundfahrt greatundoing
SERVERPROBLEMS := helloworld immortalgame greatundoing twistylittlepassages
SECRETSUFFIX := This is the secret suffix for generating flags for the main contest

include ../make/contest.mk
